### ISSUE TITLE
Legal question

### ISSUE THREAD

**Issue by willzyx-hub** [notkohlrexo/Annabelle-Ransomware#3]
Hello dev i want to ask IS IT LEGAL TO PRANK FRIENDS USING THIS VIRUS ?

**Comment by willzyx-hub** [comment]
I mean is it illegal to do it from Local law side ?

**Comment by pankoza2-pl** [comment]
It's illegal, because this ransomware will encrypt all the files, and eventually damage MBR (Master Boot Record) to make computer unbootable

**Comment by willzyx-hub** [comment]
> It's illegal, because this ransomware will encrypt all the files, and eventually damage MBR (Master Boot Record) to make computer unbootable

Ok Thanks for the information.
